// Insteon 915 MHz RF listener: what every listener board shares.
//
// Receive only. There is exactly one transmitter on an Insteon network and it
// is the PLM; a second one would collide with it. No radio driver here has a
// transmit path at all, deliberately.
//
// A radio driver's whole job is to hand process_capture_() the bytes that
// followed the Insteon start header, plus the RSSI and the moment the first
// of those bits was on the air. Everything after that -- the Manchester gate,
// the RSSI floor, the MQTT payload and its timestamp, the counters, the
// sensors and the read-outs for an on-board display -- lives here, so two
// boards with different radios publish captures the host cannot tell apart
// except by name.
//
// Drivers:
//   sx1262.h  Heltec LoRa 32 V3 (SX1262), GFSK packet mode as a bit recorder
//   cc1101.h  LilyGO T-Embed CC1101 (CC1101), the CC1111 dongle's own modem

#pragma once

#include "esphome/core/component.h"
#include "esphome/core/hal.h"
#include "esphome/core/helpers.h"

#include <cmath>
#include <cstdint>
#include <string>

#ifdef USE_SENSOR
#include "esphome/components/sensor/sensor.h"
#endif

namespace esphome {
namespace insteon_rf {

// Generated by tools/gen_sync_word.py from Packet.to_bits(), which is
// validated against real devices, and pinned by tests/test_sync_word.py.
// Four preamble cells then the inverted START_HEADER; the low 16 bits are
// 0x3155, which is exactly what the CC1111 dongle syncs on.
//
// This is the default; the YAML `sync_word:` option overrides it. If the
// SX1262's bit sense turns out opposite to the CC1111's, the complement
// 0xCCCCCEAA is the word to try -- a wrong polarity looks exactly like a
// wiring fault (no captures, no errors), so it must be flippable over OTA.
static const uint32_t INSTEON_SYNC_WORD = 0x33333155;
// How much of it the radio matches on, from the low end: 16 is the start
// header alone (what the CC1111 dongle uses), 24 adds two preamble cells, 32
// adds four. Insteon sends only about five cells of preamble, and every cell
// the sync word swallows is one the bit synchroniser no longer has to lock
// on before matching starts. Measured 2026-09-28: at 32 the board synced on
// about 10 transmissions a minute while the dongle decoded far more.
static const uint8_t INSTEON_SYNC_BITS = 32;

// Insteon on-air parameters.
static const uint32_t INSTEON_BITRATE = 9124;
static const uint32_t INSTEON_DEVIATION_HZ = 75000;

/// Microseconds of air for n bytes at the Insteon bit rate.
inline uint32_t air_us(uint32_t nbytes) {
  return (uint32_t) (((uint64_t) nbytes * 8ULL * 1000000ULL) / INSTEON_BITRATE);
}

class InsteonRF : public Component {
 public:
  float get_setup_priority() const override { return setup_priority::DATA; }

  void set_sync_word(uint32_t word) { this->sync_word_ = word; }
  void set_capture_bytes(uint8_t n) { this->capture_bytes_ = n; }
  void set_rssi_floor(float dbm) { this->rssi_floor_ = dbm; }
  void set_manchester_gate(uint8_t frames) { this->manchester_gate_ = frames; }
  void set_manchester_gate_errors(uint8_t n) { this->manchester_gate_errors_ = n; }
  void set_mqtt_topic(const std::string &topic) { this->mqtt_topic_ = topic; }

#ifdef USE_SENSOR
  void set_last_rssi_sensor(sensor::Sensor *s) { this->last_rssi_sensor_ = s; }
  void set_captures_sensor(sensor::Sensor *s) { this->captures_sensor_ = s; }
  void set_accepted_sensor(sensor::Sensor *s) { this->accepted_sensor_ = s; }
  // Only radios that measure these publish them (the CC1101 does).
  void set_frequency_offset_sensor(sensor::Sensor *s) { this->frequency_offset_sensor_ = s; }
  void set_lost_sensor(sensor::Sensor *s) { this->lost_sensor_ = s; }
#endif

  // -- read-outs for an on-board display (placement survey)
  bool radio_ok() const { return this->radio_ok_; }
  float last_rssi() const { return this->last_rssi_; }
  /// RSSI of the last capture that passed the gate, i.e. the last real
  /// Insteon packet; NAN until one has.
  float last_accepted_rssi() const { return this->last_accepted_rssi_; }
  uint32_t total_captures() const { return this->captures_; }
  uint32_t total_accepted() const { return this->accepted_; }
  /// Counts over the previous whole minute, refreshed once a minute.
  uint32_t captures_last_minute() const { return this->captures_last_minute_; }
  uint32_t accepted_last_minute() const { return this->accepted_last_minute_; }
  /// Captures the radio lost before the gate saw them, previous minute.
  uint32_t lost_last_minute() const { return this->lost_last_minute_; }
  /// Mean carrier offset of the previous minute's accepted packets, kHz;
  /// NAN when the radio cannot measure it or nothing was accepted.
  float frequency_offset_khz() const { return this->freq_offset_last_minute_; }
  /// Milliseconds since the last accepted capture, or UINT32_MAX if none.
  uint32_t ms_since_accepted() const {
    return this->last_accepted_ms_ ? millis() - this->last_accepted_ms_ : UINT32_MAX;
  }

 protected:
  /// Gate, filter and publish one capture. `buf` starts with the first bit
  /// after the start header; `first_bit_us` is micros() when that bit was on
  /// the air; `offset_khz` is the radio's carrier-offset estimate, or NAN.
  void process_capture_(const uint8_t *buf, size_t len, float rssi, uint32_t first_bit_us,
                        float offset_khz = NAN);
  /// Roll the per-minute counters and publish the rate sensors.
  void tick_minute_();
  /// The radio lost a capture (FIFO overflow, full hand-off queue, ...).
  void count_lost_(uint32_t n = 1) { this->lost_ += n; }
  void dump_common_config_();

  bool manchester_gate_ok_(const uint8_t *buf, size_t len) const;
  void publish_capture_(const uint8_t *buf, size_t len, float rssi, uint32_t first_bit_us);

  uint32_t sync_word_{INSTEON_SYNC_WORD};
  uint8_t capture_bytes_{162};
  float rssi_floor_{-110.0f};
  uint8_t manchester_gate_{4};
  uint8_t manchester_gate_errors_{2};
  std::string mqtt_topic_{};

  bool radio_ok_{false};
  uint32_t seq_{0};
  uint32_t captures_{0};
  uint32_t accepted_{0};
  uint32_t lost_{0};
  uint32_t last_minute_mark_{0};
  uint32_t captures_at_mark_{0};
  uint32_t accepted_at_mark_{0};
  uint32_t lost_at_mark_{0};
  uint32_t captures_last_minute_{0};
  uint32_t accepted_last_minute_{0};
  uint32_t lost_last_minute_{0};
  float freq_offset_sum_{0.0f};
  uint32_t freq_offset_n_{0};
  float freq_offset_last_minute_{NAN};
  float last_rssi_{NAN};
  float last_accepted_rssi_{NAN};
  uint32_t last_accepted_ms_{0};
  //: The first few captures are logged at INFO with their leading bytes, so
  //: bring-up can be judged from the log alone: are captures arriving, does
  //: the gate pass them, does the polarity look right.
  uint8_t bringup_logged_{0};

#ifdef USE_SENSOR
  sensor::Sensor *last_rssi_sensor_{nullptr};
  sensor::Sensor *captures_sensor_{nullptr};
  sensor::Sensor *accepted_sensor_{nullptr};
  sensor::Sensor *frequency_offset_sensor_{nullptr};
  sensor::Sensor *lost_sensor_{nullptr};
#endif
};

}  // namespace insteon_rf
}  // namespace esphome
